### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by thedavecarroll** [jscarle/OnePassword.NET#21]
Greetings. I'm in the beginning stages of writing a PowerShell module to work with 1Password. I had started down the path of creating C# classes but during some searching, I discovered this library.

To support app CLI integration, I made a couple small changes which are working in my local copy. I would like to have these included and wanted to know how you would like me to proceed. I can create a PR or provide the code addition.

Also, I encountered a deserialization error when retrieving my account which is `Family` type. I've submitted a 1Password community forum question asking for the list of possible account types so your enum could be more complete.

This library saved me a lot of work and I really appreciate the work that you put into it.

Thank you.
Dave

**Comment by jscarle** [comment]
Hello Dave!

I'm glad that this library has been useful for you.

You can absolutely make a pull request and I'll take a look at integrating the changes.

As for the account deserialization error, I'll fix that. Unfortunately most of the enums that are used within the library had to be sniffed through exhaustive and repetitive CLI commands, so there may be a few missing values such as the one you found. That's why community usage and testing is so valuable on these types of projects.

**Comment by jscarle** [comment]
The Family account type has been added to release v2.1.1.
